# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-kms-key
  description: Terraform module to provision a KMS key with alias
  homepage: https://cloudposse.com/accelerate
  topics: terrafrom, terraform-modules, kms-key, chamber, provision, aws, systems-management, parameter-store, ssm, kms, hcl2


